bigmark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('potshop.urls', namespace='potshop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

potshop/urls.py
from django.urls import path
from potshop import views
from .views import add_to_cart, remove_from_cart, remove_single_item_from_cart

app_name='potshop'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home-page'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('store/', views.StorePageView.as_view(), name='store'),
    path('lookbook/', views.BookPageView.as_view(), name='lookbook'),
    path('product/<slug>/', views.productPageView.as_view(), name='product'),
    path('checkout/', views.CheckoutPageView.as_view(), name='checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

potshop/models.py
from django.conf import settings
from django.db import models
import datetime
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sports wear'),
    ('OW', 'Outwear'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)
# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price= models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("potshop:product", kwargs={
            "slug": self.slug
        })
        
    def get_add_to_cart(self):
        return reverse("potshop:add-to-cart", kwargs={
            'slug':self.slug
        })
    
    def get_remove_from_cart(self):
        return reverse("potshop:remove-from-cart", kwargs={
            'slug':self.slug
        })
        

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.product.price

    def get_total_discount_item_price(self):
        return self.quantity * self.product.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.product.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress',on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.product.all():
            total += order_item.get_final_price()
        return total
    
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

potshop/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = {
    ('S', 'Stripe'),
    ('P', 'PayPal')
}

class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder' : '1234 Main St'
    }))
    apartment = forms.CharField(required=False,widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder' : 'Apartment or Suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class':'custom-select d-block w-100'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

potshop/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from django.shortcuts import redirect
from django.utils import timezone
from .models import Product, OrderItem, Order, BillingAddress
from .forms import CheckoutForm

# Create your views here.
# def item_list(request):
#     context = {
#         'items': Product.object.all()
#     }
#     return render(request, "item_list.html", context)

class HomePageView(TemplateView):
    template_name = "home.html"
    
class AboutPageView(TemplateView):
    template_name = "about.html"
    
class StorePageView(ListView):
    model = Product
    paginate_by = 10
    template_name = "shop.html"
    
    
class OrderSummaryView(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered = False)
            context = {
                'object':order
            }
            return render(self.request, "order-summary.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("/store")
        
    
class BookPageView(TemplateView):
    template_name = "look-book.html"
    
class productPageView(DetailView):
    model = Product
    template_name = "product-page.html"
    
@login_required  
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False
        )
    
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item was added to your cart")
            
        else:
            
            order.product.add(order_item)
            messages.info(request, "This item was added to your cart")
            return redirect("potshop:order-summary")
        
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.product.add(order_item)
        return redirect("potshop:order-summary")
        
    return redirect("potshop:order-summary")


@login_required  
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            order.product.remove(order_item)
            messages.info(request, "This item was removed from your cart")
            return redirect("potshop:order-summary")
        else:
            #order does not have this order item
            messages.info(request, "This item was not in your cart")
            return redirect("potshop:product", slug=slug)
    else:
        #the user doesn't have an order
        messages.info(request, "You do not have an active order")
        return redirect("potshop:product", slug=slug)



@login_required  
def remove_single_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.product.remove(order_item)
            messages.info(request, "This item was updated")
        else:
            #order does not have this order item
            messages.info(request, "This item was not in your cart")
            return redirect("potshop:order-summary")
    else:
        #the user doesn't have an order
        messages.info(request, "You do not have an active order")
        return redirect("potshop:product", slug=slug)
    return redirect("potshop:order-summary")

    
class CheckoutPageView(View):
    def get(self, *args, **kwargs):
        # form
        form = CheckoutForm()
        
        context = {
            'form' : form
        }
        return render(self.request, "checkout-page.html", context)
    
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered = False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment = form.cleaned_data.get('apartment')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                # TODO: add functionality
                # same_shipping_address = form.cleaned_data.get('same_shipping_address')
                # save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip=zip
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                # TODO: add redirect to the selected payment option
                return redirect('potshop:checkout')
            
            messages.warning(self.request, "Failed checkout")
            return redirect('potshop:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("core:order-summary")
        
        
        

potshop/templates/partials/footer.html
<!-- Footer -->
<footer class="page-footer font-small unique-color-dark pb-0 mb-0 w-100">

  <div style="background-color: #6f367a;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0" style="color:white;">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold" style="color:white;">Company name</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold" style="color:white;">Products</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">MDBootstrap</a>
        </p>
        <p>
          <a href="#!">MDWordPress</a>
        </p>
        <p>
          <a href="#!">BrandFlow</a>
        </p>
        <p>
          <a href="#!">Bootstrap Angular</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold" style="color:white;">Useful links</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">Your Account</a>
        </p>
        <p>
          <a href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a href="#!">Shipping Rates</a>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold" style="color:white;">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> markopondo.m@gmail.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> +254795133547</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->

potshop/templates/partials/nav-bar.html
{% load cart_template_tags  %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light unique-color-dark scrolling-navbar pt-4">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'potshop:home-page' %}">
      <strong class="purple-text" style="color: #6f367a;">BigMark</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" style="background: #afafaf" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" style="color:white;"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'potshop:about' %}">About
            <span class="sr-only">(current)</span>
          </a>
        </li> {% endcomment %}
        <li class="nav-item">
          <a class="nav-link waves-effect" style="color:white;" href="{% url 'potshop:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" style="color:white;" href="{% url 'potshop:store' %}">Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" style="color:white;" href="{% url 'potshop:lookbook' %}">Look Book</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'potshop:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 1 </span>
              <i class="fas fa-shopping-cart" style="color:#6f367a;"></i>
              <span class="clearfix d-none d-sm-inline-block" style="color:white;"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block" style="color:white;"> Logout </span>
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block" style="color:white;"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block" style="color:white;"> SignUp </span>
            </a>
          </li>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

potshop/templates/partials/news-letter.html
{% comment %} <form class="container">
    <div class="col-md-8 mx-auto text-center border border-light p-5 align-items-center">
        <div class="row">
            <div class="col-md-8 pb-2">
                <h1>Subscribe</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 pb-2">
                <input placeholder="Name"/>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 pb-2">
                <input placeholder="Email"/>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 pb-2">
            <button class="btn btn-primary"> Subscribe</button>
            </div>
        </div>
    <div>
</form> {% endcomment %}

<!-- Default form login -->
<form class="text-center border border-dark-ic p-5 w-50 mx-auto mt-5" action="#!">

    <p class="h4 mb-5">Subscribe</p>
    <p>Subscribe to our newsletter to recieve the latest updates on our store !</p>

    <!-- Name -->
    <input type="email" id="defaultLoginFormEmail" class="form-control mb-5" placeholder="Name">

    <!-- Email -->
    <input type="password" id="defaultLoginFormPassword" class="form-control mb-5" placeholder="Email">


    <!-- Subscribe button -->
    <button class="btn btn-purple w-50" style="color: white;" type="submit">Subscribe</button>



</form>
<!-- Default form login -->