bigmark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('potshop.urls', namespace='potshop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

potshop/urls.py
from django.urls import path
from potshop import views
from .views import add_to_cart, remove_from_cart, remove_single_item_from_cart

app_name='potshop'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home-page'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('store/', views.StorePageView.as_view(), name='store'),
    path('lookbook/', views.BookPageView.as_view(), name='lookbook'),
    path('product/<slug>/', views.productPageView.as_view(), name='product'),
    path('checkout/', views.CheckoutPageView.as_view(), name='checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

potshop/models.py
from django.conf import settings
from django.db import models
import datetime
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sports wear'),
    ('OW', 'Outwear'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)
# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price= models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("potshop:product", kwargs={
            "slug": self.slug
        })
        
    def get_add_to_cart(self):
        return reverse("potshop:add-to-cart", kwargs={
            'slug':self.slug
        })
    
    def get_remove_from_cart(self):
        return reverse("potshop:remove-from-cart", kwargs={
            'slug':self.slug
        })
        

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.product.price

    def get_total_discount_item_price(self):
        return self.quantity * self.product.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.product.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress',on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.product.all():
            total += order_item.get_final_price()
        return total
    
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

potshop/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = {
    ('S', 'Stripe'),
    ('P', 'PayPal')
}

class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder' : '1234 Main St'
    }))
    apartment = forms.CharField(required=False,widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder' : 'Apartment or Suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class':'custom-select d-block w-100'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

potshop/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from django.shortcuts import redirect
from django.utils import timezone
from .models import Product, OrderItem, Order, BillingAddress
from .forms import CheckoutForm

# Create your views here.
# def item_list(request):
#     context = {
#         'items': Product.object.all()
#     }
#     return render(request, "item_list.html", context)

class HomePageView(TemplateView):
    template_name = "home.html"
    
class AboutPageView(TemplateView):
    template_name = "about.html"
    
class StorePageView(ListView):
    model = Product
    paginate_by = 10
    template_name = "shop.html"
    
    
class OrderSummaryView(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered = False)
            context = {
                'object':order
            }
            return render(self.request, "order-summary.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("/store")
        
    
class BookPageView(TemplateView):
    template_name = "look-book.html"
    
class productPageView(DetailView):
    model = Product
    template_name = "product-page.html"
    
@login_required  
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False
        )
    
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item was added to your cart")
            
        else:
            
            order.product.add(order_item)
            messages.info(request, "This item was added to your cart")
            return redirect("potshop:order-summary")
        
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.product.add(order_item)
        return redirect("potshop:order-summary")
        
    return redirect("potshop:order-summary")


@login_required  
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            order.product.remove(order_item)
            messages.info(request, "This item was removed from your cart")
            return redirect("potshop:order-summary")
        else:
            #order does not have this order item
            messages.info(request, "This item was not in your cart")
            return redirect("potshop:product", slug=slug)
    else:
        #the user doesn't have an order
        messages.info(request, "You do not have an active order")
        return redirect("potshop:product", slug=slug)



@login_required  
def remove_single_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    
    if order_qs.exists():
        order = order_qs[0]
        
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.product.remove(order_item)
            messages.info(request, "This item was updated")
        else:
            #order does not have this order item
            messages.info(request, "This item was not in your cart")
            return redirect("potshop:order-summary")
    else:
        #the user doesn't have an order
        messages.info(request, "You do not have an active order")
        return redirect("potshop:product", slug=slug)
    return redirect("potshop:order-summary")

    
class CheckoutPageView(View):
    def get(self, *args, **kwargs):
        # form
        form = CheckoutForm()
        
        context = {
            'form' : form
        }
        return render(self.request, "checkout-page.html", context)
    
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered = False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment = form.cleaned_data.get('apartment')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                # TODO: add functionality
                # same_shipping_address = form.cleaned_data.get('same_shipping_address')
                # save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip=zip
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                # TODO: add redirect to the selected payment option
                return redirect('potshop:checkout')
            
            messages.warning(self.request, "Failed checkout")
            return redirect('potshop:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("core:order-summary")
        
        
        

potshop/templates/about.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}About Us {% endblock %}</title>
</head>
<body>
    {% block content %}
        <h1>About Us</h1>
    {% endblock %}

</body>
</html>

potshop/templates/home.html
{% extends 'base.html' %}

{% block head_title %}Welcome Home {% endblock %}</title>

{% block content %}
<div class='container col-md-12 p-0 m-0 pb-4'>
		<!--Carousel Wrapper-->
	<div id="carousel-thumb" data-ride="carousel">
		<div class="carousel-inner h-50 pb-5" role="listbox">
			<div class="carousel-item">
			<img class="d-block w-100" src="/media/beautiful-body-dress-944761 (2).jpg"
				alt="First slide">
			</div>
			<div class="carousel-item">
			<img class="d-block w-100" src="/media/apparel-attire-blur-994517 (2).jpg"
				alt="Second slide">
			</div>
			<div class="carousel-item">
			<img class="d-block w-100" src="/media/adult-footwear-girl-893962 (4).jpg"
				alt="Third slide">
			</div>
			<div class="carousel-item">
			<img class="d-block w-100" src="/media/child-city-daytime-955341 (1).jpg"
				alt="Third slide">
			</div>
		</div>
	</div>
	<!--/.Carousel Wrapper-->

	<!--Store-->

		<!-- News jumbotron -->
	<div id="links" class="jumbotron text-center hoverable p-4">

	<!-- Grid row -->
	<div class="row">

		<!-- Grid column -->
		<div class="col-md-4 offset-md-1 mx-3 my-3">

		<!-- Featured image -->
		<div class="view overlay">
			<img src="/media/closet-clothes-colors-581087.jpg" class="img-fluid" alt="Sample image for first version of blog listing">
			<a>
			<div class="mask rgba-white-slight"></div>
			</a>
		</div>

		</div>
		<!-- Grid column -->

		<!-- Grid column -->
		<div class="col-md-7 text-md-left ml-3 mt-3">

		<!-- Excerpt -->
		<a href="{% url 'potshop:store'%}" class="green-text">
			<h4 class="h4 pb-1"><i class="fas fa-desktop pr-1"></i> Store</h4>
		</a>

		<h4 class="h4 mb-4">This is title of the news</h4>

		<p class="font-weight-normal">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque, totam
			rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
			dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.</p>
		<p class="font-weight-normal">by <a><strong>Carine Fox</strong></a>, 19/08/2016</p>

		<a class="btn btn-purple" style="color: white;" href="{% url 'potshop:store'%}">Shop</a>

		</div>
		<!-- Grid column -->

	</div>
	<!-- Grid row -->

	</div>
	<!-- News jumbotron -->


	<!--Look Book-->

		<!-- News jumbotron -->
	<div id="links" class="jumbotron text-center hoverable p-4">

		<!-- Grid row -->
		<div class="row">

			<!-- Grid column -->
			<div class="col-md-4 offset-md-1 mx-3 my-3">

			<!-- Featured image -->
			<div class="view overlay">
				<img src="/media/buildings-casual-city-1579019.jpg" class="img-fluid" alt="Sample image for first version of blog listing">
				<a>
				<div class="mask rgba-white-slight"></div>
				</a>
			</div>

			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-7 text-md-left ml-3 mt-3">

			<!-- Excerpt -->
			<a href="{% url 'potshop:lookbook'%}" class="green-text">
				<h4 class="h4 pb-1"><i class="fas fa-desktop pr-1"></i> Look Book</h4>
			</a>

			<h4 class="h4 mb-4">This is title of the news</h4>

			<p class="font-weight-normal">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque, totam
				rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
				dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.</p>
			<p class="font-weight-normal">by <a><strong>Carine Fox</strong></a>, 19/08/2016</p>

			<a class="btn btn-purple" style="color: white;" href="{% url 'potshop:lookbook'%}">Look Book</a>

			</div>
			<!-- Grid column -->

		</div>
		<!-- Grid row -->

	</div>
	<!-- News jumbotron -->


	<!--About-->
		<!-- News jumbotron -->
	<div id="links" class="jumbotron text-center hoverable p-4">

		<!-- Grid row -->
		<div class="row">

			<!-- Grid column -->
			<div class="col-md-4 offset-md-1 mx-3 my-3">

			<!-- Featured image -->
			<div class="view overlay">
				<img src="/media/adult-collaboration-colleagues-1308780.jpg" class="img-fluid" alt="Sample image for first version of blog listing">
				<a>
				<div class="mask rgba-white-slight"></div>
				</a>
			</div>

			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-7 text-md-left ml-3 mt-3">

			<!-- Excerpt -->
			<a href="{% url 'potshop:about'%}" class="green-text">
				<h4 class="h4 pb-1"><i class="fas fa-desktop pr-1"></i> About</h4>
			</a>

			<h4 class="h4 mb-4">This is title of the news</h4>

			<p class="font-weight-normal">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque, totam
				rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
				dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.</p>
			<p class="font-weight-normal">by <a><strong>Carine Fox</strong></a>, 19/08/2016</p>

			<a class="btn btn-purple" style="color: white;" href="{% url 'potshop:about'%}">About Us</a>

			</div>
			<!-- Grid column -->

		</div>
		<!-- Grid row -->

	</div>
	<!-- News jumbotron -->

	<!--Contact-->
		<!-- News jumbotron -->
	<div id="links" class="jumbotron text-center hoverable p-4">

		<!-- Grid row -->
		<div class="row">

			<!-- Grid column -->
			<div class="col-md-4 offset-md-1 mx-3 my-3">

			<!-- Featured image -->
			<div class="view overlay">
				<img src="/media/connection-contact-focus-955081.jpg" class="img-fluid" alt="Sample image for first version of blog listing">
				<a>
				<div class="mask rgba-white-slight"></div>
				</a>
			</div>

			</div>
			<!-- Grid column -->

			<!-- Grid column -->
			<div class="col-md-7 text-md-left ml-3 mt-3">

			<!-- Excerpt -->
			<a href="#" class="green-text">
				<h4 class="h4 pb-1"><i class="fas fa-desktop pr-1"></i> Contact</h4>
			</a>

			<h4 class="h4 mb-4">This is title of the news</h4>

			<p class="font-weight-normal">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque, totam
				rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
				dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.</p>
			<p class="font-weight-normal">by <a><strong>Carine Fox</strong></a>, 19/08/2016</p>

			<a class="btn btn-purple">Reach Out</a>

			</div>
			<!-- Grid column -->

		</div>
		<!-- Grid row -->

	</div>
	<!-- News jumbotron -->

	{% include 'partials/news-letter.html' %}


</div>


<script>
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("carousel-item");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}    
  x[myIndex-1].style.display = "block";  
  setTimeout(carousel, 3000); // Change image every 2 seconds
}
</script>
{% endblock %}  

potshop/templates/look-book.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Look Book{% endblock %}</title>
</head>
<body>

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center mt-5 pt-5">
            <h1>Look Book</h1>
        </div>
    </div>
    <!-- Grid row -->
    <div class="row"> 

    {% comment %} <!-- Grid column -->
    <div class="col-md-12 d-flex justify-content-center mb-5 mt-1 pt-4">

        <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="all">All</button>
        <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="1">Mountains</button>
        <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="2">Sea</button>

    </div>
    <!-- Grid column --> {% endcomment %}

    </div>
    <!-- Grid row -->

    <!-- Grid row -->
    <div class="gallery w-75 mx-auto mb-5 pb-4" id="gallery">

        <!-- Grid column -->
        <div class="mb-3 pics animation all 2">
            <img class="img-fluid" src="/media/adult-art-black-t-shirt-1656684.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/adult-collaboration-colleagues-1308780.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/adults-architecture-buildings-1888306 (2).jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 2">
            <img class="img-fluid" src="/media/casual-daylight-eyewear-2872929.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 2">
            <img class="img-fluid" src="/media/black-jeans-design-fashion-1933589.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/attractive-beautiful-beauty-1771383.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/fashion-man-outfit-2180895.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/fashion-female-girl-1374913.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="mb-3 pics animation all 1">
            <img class="img-fluid" src="/media/child-city-daytime-955341.jpg" alt="Card image cap">
        </div>
        <!-- Grid column -->
    </div>
</div>

<!-- Grid row -->

<script>
$(function() {
var selectedClass = "";
$(".filter").click(function(){
selectedClass = $(this).attr("data-rel");
$("#gallery").fadeTo(100, 0.1);
$("#gallery div").not("."+selectedClass).fadeOut().removeClass('animation');
setTimeout(function() {
$("."+selectedClass).fadeIn().addClass('animation');
$("#gallery").fadeTo(300, 1);
}, 300);
});
});
</script>
{% endblock %}    

{% comment %} <script>
$(function() {
var selectedClass = "";
$(".filter").click(function(){
selectedClass = $(this).attr("data-rel");
$("#gallery").fadeTo(100, 0.1);
$("#gallery div").not("."+selectedClass).fadeOut().removeClass('animation');
setTimeout(function() {
$("."+selectedClass).fadeIn().addClass('animation');
$("#gallery").fadeTo(300, 1);
}, 300);
});
});
</script> {% endcomment %}

</body>
</html>

potshop/templates/order-summary.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class="container">
        <div class="table-responsive text-nowrap w-100 mx-auto">
            <h2 class="pt-3">Order Summary</h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in object.product.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.product.title }}</td>
                    <td>Ksh {{ order_item.product.price }}</td>

                    <td>
                        <a href="{% url "potshop:remove-single-item-from-cart" order_item.product.slug %}"><i class="far fa-minus-square mr-2"></i></a>
                            {{ order_item.quantity }}
                        <a href="{% url "potshop:add-to-cart" order_item.product.slug %}"><i class="far fa-plus-square ml-2"></i></a>
                    </td>

                    <td>
                    {% if order_item.product.discount_price%}
                        Ksh {{ order_item.get_total_discount_item_price }}
                        <span class="badge badge-primary">Saving Ksh {{ order_item.get_amount_saved }}</span>
                    {% else %}
                        Ksh {{ order_item.get_total_item_price }}
                    {% endif %}
                    <a style="color: red;" href="{% url "potshop:remove-from-cart" order_item.product.slug %}"><i class="fas fa-trash-alt float-right"></i></a>
                    </td>
                    
                </tr>
                
                {% endfor %}
                <tr>
                    <td colspan="4">Order Total</td>
                    <td><b>Ksh {{ object.get_total }}</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed To Checkout</a>
                    <a class="btn btn-primary float-right" href="/store/">Continue Shopping</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

{% endblock content %}

potshop/templates/shop.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Shop {% endblock %}</title>
</head>
<body>
    {% block content %}
        <!--Grid row-->
        <div class="row wow fadeIn w-75 mx-auto">
          {% for product in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mt-3 pt-2 h-25">
            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a href="{{ product.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{product.title}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ product.get_absolute_url }}" class="dark-grey-text">Denim shirt
                      <span class="badge badge-pill {{ product.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                  {% if product.discount_price %}
                  ksh{{product.discount_price}}
                  {% else %}
                  ksh{{product.price}}
                  {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->
         <!--Pagination-->
        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
            
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
      <!--Pagination-->
      {% endif%}
    {% endblock %}

</body>
</html>